---
- name: DEPLOY AS3 DEC
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    uri_method: POST
  
  vars_files:
    - ../creds/f5.yaml

  tasks:

  - name: Create AS3 Template
    uri:
      url: https://35.179.86.82/mgmt/shared/appsvcs/declare
      user: "{{ f5username }}"
      password: "{{ f5password }}"
      method: "{{ uri_method }}"
      body: "{{ lookup('file','AS3.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
    register: as3_response

  - name: DEBUG OUTPUT AS3 RESPONSE
    debug:
      msg: "{{as3_response}}"   
  - name: DEBUG OUTPUT AS3 RESPONSE
    debug:
      msg: "Content Length = {{as3_response.content_length}}"


...